"""Second

Revision ID: eb367ad10e5d
Revises: 7f4f0530ca3a
Create Date: 2023-01-26 17:22:50.817437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb367ad10e5d'
down_revision = '7f4f0530ca3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterednumbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterednumbers_id'), 'enterednumbers', ['id'], unique=True)
    op.create_table('primefactors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prfactors', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_primefactors_id'), 'primefactors', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_primefactors_id'), table_name='primefactors')
    op.drop_table('primefactors')
    op.drop_index(op.f('ix_enterednumbers_id'), table_name='enterednumbers')
    op.drop_table('enterednumbers')
    # ### end Alembic commands ###
